name: Test

on:
  pull_request:

jobs:
  unit:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go_version:
          - 1.20
          - 1.21
          - 1.22
          - 1.23
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go_version }}
      - run: go mod download
      - run: go test ./...
